# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [3]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
arr=np.random.randint(1,21,size=(5,5))
arr[2]=1
print(arr)

[[ 4 13  4  6 17]
 [17 17 19  4 14]
 [ 1  1  1  1  1]
 [ 3 17 12 20 18]
 [19 14 14 13  8]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [5]:
arr=np.random.randint(1,16,size=(4,4))
np.fill_diagonal(arr,0)
print(arr)

[[ 0 13  9  1]
 [ 9  0  6  6]
 [14  1  0  9]
 [13  6  8  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [6]:
arr=np.random.randint(1,37,size=(6,6))
print(arr[2:5,1:4])
print(arr)

[[14 27 29]
 [11 11 22]
 [10 31 36]]
[[12 12  8 32 20 31]
 [36 24 32  7 12  1]
 [12 14 27 29 36 10]
 [ 8 11 11 22  1 26]
 [36 10 31 36 36 25]
 [ 8 31 34 33 18 24]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [15]:
arr=np.random.randint(0,26,size=(5,5))
print(arr)
print('left')
print(arr[0:,0])
print('top')
print(arr[0,0:])
print('bottom')
print(arr[-1:,0:])
print('right')
print(arr[0:,-1])

[[23 23  5 15 16]
 [23 14  5  6 11]
 [12 24 15  6 10]
 [13  1  2 21 11]
 [17 11 24 23 18]]
left
[23 23 12 13 17]
top
[23 23  5 15 16]
bottom
[[17 11 24 23 18]]
right
[16 11 10 11 18]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [19]:
arr1=np.random.randint(1,13,size=(3,4))
arr2=np.random.randint(0,13,size=(3,4))

print('arr1')
print(arr1)
print('arr2')
print(arr2)
print('Addition')
print(arr1+arr2)
print('Subs')
print(arr1-arr2)
print('mul')
print(arr1*arr2)
print('div')
print(arr1//arr2)

arr1
[[ 9  8  1  8]
 [11  3  1  9]
 [ 2  3  7  1]]
arr2
[[5 2 2 7]
 [6 7 6 7]
 [2 2 6 8]]
Addition
[[14 10  3 15]
 [17 10  7 16]
 [ 4  5 13  9]]
Subs
[[ 4  6 -1  1]
 [ 5 -4 -5  2]
 [ 0  1  1 -7]]
mul
[[45 16  2 56]
 [66 21  6 63]
 [ 4  6 42  8]]
div
[[1 4 0 1]
 [1 0 0 1]
 [1 1 1 0]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [4]:
arr=np.random.randint(1,17,size=(4,4))
print(arr)
rows=arr.sum(axis=1)
col=arr.sum(axis=0)
print(f"cols: {rows}")
print(f"rows: {col}")

[[10  7  4  7]
 [ 6  6  7  5]
 [ 7  9  7  3]
 [ 9  6  9 13]]
cols: [28 24 26 37]
rows: [32 28 27 28]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [6]:
arr=np.random.randint(1,26,size=(5,5))
print(arr)
print(f"Mean: {np.mean(arr)}")
print(f"median: {np.median(arr)}")
print(f"standard Deviation: {np.std(arr)}")
print(f"variance: {np.var(arr)}")

[[ 7 23  1  6  8]
 [ 9 12 19 10 24]
 [21 25 24 21 15]
 [20 22 10 14 14]
 [13  5 20 18  9]]
Mean: 14.8
median: 14.0
standard Deviation: 6.776429738438967
variance: 45.92000000000001


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [7]:
arr=np.random.randint(1,10,size=(3,3))
means=np.mean(arr)
stdDev=np.std(arr)
normalArr=(arr-means)/stdDev
print(normalArr)

[[-1.39754249 -0.3913119  -0.89442719]
 [ 1.11803399 -1.39754249  1.11803399]
 [ 1.11803399  0.1118034   0.61491869]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [15]:
arr=np.random.randint(1,10,size=(3,3))
arr1=np.random.randint(1,4,size=3)
print(arr)
print(arr1)
res=arr+arr1
print(res)

[[6 6 9]
 [7 9 2]
 [9 6 4]]
[2 1 3]
[[ 8  7 12]
 [ 9 10  5]
 [11  7  7]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [16]:
arr=np.random.randint(1,17,size=(4,4))
arr1=np.random.randint(1,5,size=4)

print(arr)
print(arr1)
res=arr-arr1
print(res)

[[ 9 10  7 13]
 [15  1  7 15]
 [ 6  3 14 10]
 [ 2  3 12  3]]
[2 4 3 4]
[[ 7  6  4  9]
 [13 -3  4 11]
 [ 4 -1 11  6]
 [ 0 -1  9 -1]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [6]:
arr=np.random.randint(1,10,size=(3,3))
print(arr)
print(np.linalg.det(arr))
print(np.linalg.inv(arr))
print(np.linalg.eigvals(arr))

[[2 2 3]
 [9 2 7]
 [2 4 1]]
54.00000000000003
[[-0.48148148  0.18518519  0.14814815]
 [ 0.09259259 -0.07407407  0.24074074]
 [ 0.59259259 -0.07407407 -0.25925926]]
[ 9.9612988  -1.62470454 -3.33659427]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [7]:
arr1=np.random.randint(1,7,size=(2,3))
arr2=np.random.randint(1,7,size=(3,2))
print(arr1@arr2)

[[52 56]
 [27 35]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [9]:
arr=np.random.randint(1,9,size=(3,3))
a1=arr.reshape(1,9)
a2=arr.reshape(9,1)
print(a1)
print(a2)

[[6 2 5 3 4 3 3 2 6]]
[[6]
 [2]
 [5]
 [3]
 [4]
 [3]
 [3]
 [2]
 [6]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [11]:
arr=np.random.randint(1,25,size=(5,5))
a1=arr.reshape(1,25)
print(a1)
a2=arr.reshape(5,5)
print(a2)

[[23 15 24 24 13  1 17 18 23 19  4 14  1 23 13  6  2 20 16  9 24 12  1 13
  17]]
[[23 15 24 24 13]
 [ 1 17 18 23 19]
 [ 4 14  1 23 13]
 [ 6  2 20 16  9]
 [24 12  1 13 17]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [14]:
arr=np.random.randint(1,25,size=(5,5))
print(arr)
corner=arr[[0,0,-1,-1],[0,-1,0,-1]]
print(corner)

[[16 16 12  5  9]
 [22  9 24 11 14]
 [ 8 22 14 12 22]
 [15  5 20  5  9]
 [13 21 10 10 12]]
[16  9 13 12]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [18]:
arr=np.random.randint(1,17,size=(4,4))
arr[arr>10]=10
print(arr)

[[10 10 10 10]
 [10  2 10  4]
 [10  2 10  3]
 [ 3  8  3 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [ ]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.